storage:
  dbPath: /var/mongodb/db/node4
net:
  bindIp: localhost
  port: 27014
security:
  authorization: enabled
  keyFile: /var/mongodb/pki/dbst-keyfile
systemLog:
  destination: file
  path: /var/mongodb/logs/node4/mongod.log
  logAppend: true
processManagement:
  fork: true
replication:
  replSetName: dbst-replset