storage:
  dbPath: C:\data\db\node6
net:
  bindIp: localhost
  port: 27016
security:
  authorization: enabled
  keyFile: C:\data\pki\dbst-keyfile
systemLog:
  destination: file
  path: C:\data\logs\node6\mongod.log
  logAppend: true
replication:
  replSetName: dbst-replset