storage:
  dbPath: /var/mongodb/db/node3
net:
  bindIp: localhost
  port: 27013
security:
  authorization: enabled
  keyFile: /var/mongodb/pki/dbst-keyfile
systemLog:
  destination: file
  path: /var/mongodb/logs/node3/mongod.log
  logAppend: true
processManagement:
  fork: true
replication:
  replSetName: dbst-replset