storage:
  dbPath: C:\data\db
net:
  bindIp: localhost
  port: 27017
security:
  authorization: enabled
  keyFile: C:\data\pki\dbst-keyfile
systemLog:
  destination: file
  path: C:\data\logs\mongod.log
  logAppend: true
replication:
  replSetName: dbst-replset